---
version: '3.8'
services:

  app:
    image: tumao/paper-recommend-demo:latest
    container_name: ${NAMESPACE}-demo
    ports: 
    - 9999:80
    environment:
    - API_URL=http://api:8000
    depends_on:
    - api
    networks:
    - web
    - internal
    restart: unless-stopped

  load: &arxiv_base
    image: milvusdb/item-based-recommend:gpu-latest
    build:
      context: ./service
      dockerfile: Dockerfile
    environment:
    # - FLASK_RUN_PORT=8000
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - BERT_HOST=bert
      - BERT_PORT=5555
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MILVUS_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=milvus
      - TABLE_NAME=recommend
    volumes:
    - ./data:/opt/service/data
    # - ./model:/opt/service/model
    # - ./service:/opt/service/
    depends_on:
    - milvus
    - mysql
    - bert
    links:
    - milvus
    - mysql
    networks:
    - web
    - internal
    command: ["./docker-entrypoint.sh", "load"]
 
  api:
    <<: *arxiv_base
    ports:
    - 8000:8000
    restart: unless-stopped
    command: ["./docker-entrypoint.sh"]

  bert:
    image: bert-as-service:latest
    container_name: ${NAMESPACE}-bert
    build:
      context: .docker/bert-as-service
      dockerfile: Dockerfile
    ports:
    - 5555:5555   

  milvus:
    image: milvusdb/milvus:gpu-latest
    container_name: ${NAMESPACE}-milvus
    ports:
    - 19530:19530
    - 19121:19121
    depends_on:
    - mysql
    links:
    - mysql
    volumes:
    - ./.config/milvus:/var/lib/milvus/conf
    - ./shared/logs/milvus:/var/lib/milvus/logs
    - milvus-db:/var/lib/milvus/db
    - milvus-wal:/var/lib/milvus/wal
    networks:
    - web
    - internal
    restart: unless-stopped

  mysql:
    image: seoz/mysql-multi:5-ubuntu
    build:
      context: .docker/storage/mysql5-multi
      dockerfile: Dockerfile
    container_name: ${NAMESPACE}-multidb
    ports:
    - 3308:3306
    volumes:
    - db-data:/var/lib/mysql
    - ./.config/mysql/milvus.cnf:/etc/mysql/conf.d/my.cnf
    # - ${PWD}/shared/export/:/var/lib/mysql/export/
    networks:
    - internal
    - web
    environment:
      MYSQL_MULTIPLE_DATABASES: milvus
      MYSQL_PASSWORD: ${MILVUS_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MILVUS_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MILVUS_MYSQL_USER}
    restart: unless-stopped

networks:
  internal:
    driver: bridge
  web:
    external: true

volumes:
  db-data:
  milvus-db:
  milvus-wal:
